[global]
    workgroup = WORKGROUP
    server string = LibraryIT Server
    security = user
    map to guest = never
    access based share enum = yes 

    vfs objects = full_audit
    full_audit:prefix = %u|%I|%S
    full_audit:success = connect read write pread pwrite rename mkdir rmdir
    full_audit:failure = connect read write pread pwrite rename mkdir rmdir
    full_audit:facility = local7
    full_audit:priority = notice

[ebooks]
    path = /libraryit/ebooks
    valid users = @staff, @readonly
    write list = @staff
    read list = @readonly
    browseable = yes
    guest ok = no

[papers]
    path = /libraryit/papers
    valid users = @staff, @readonly
    write list = @staff
    read list = @readonly
    browseable = yes
    guest ok = no

[sourcecode]
    path = /libraryit/sourcecode
    valid users = @staff
    browseable = yes
    guest ok = no

[docs]
    path = /libraryit/docs
    valid users = @staff, @readonly
    write list = librarian 
    browseable = yes
    guest ok = no